<?php

/**
 * @file
 * Contains mymodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mymodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mymodule module.
    case 'help.page.mymodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function mymodule_preprocess_views_view(&$variables) {
  // add form before the view,
  // this is a alternative to print the form in DefaultController, keep only one variant
  // $form = \Drupal::formBuilder()->getForm('\Drupal\mymodule\Form\DefaultForm');
  // $variables['attachment_before'][] = $form;
}
